apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: silly-demo
  labels:
    workload-type: source-code
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/vfarcic/cartographer-demo
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 80m
      memory: 128Mi
  params:
  - name: replicas
    value: 3
  # - name: port
  #   value: 80
