---

apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  resources:
  - name: build-image
    templateRef:
      kind: ClusterImageTemplate
      name: image-builder
  - name: deploy
    templateRef:
      kind: ClusterTemplate
      name: app-deployment
    images:
    - resource: build-image
      name: buildImage
  serviceAccountRef:
    name: cartographer
    namespace: default
  selector:
    workload-type: source-code
